[theme]
base = "dark"
primaryColor = "#ff8f45"
backgroundColor = "#08111f"
secondaryBackgroundColor = "#111d34"
textColor = "#f5f8ff"
font = "sans serif"

[server]
maxUploadSize = 1024

[client]
toolbarMode = "minimal"
